/* Generated By:JavaCC: Do not edit this line. UniParserConstants.java */
package uni;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UniParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNIVERSITYNAME = 5;
  /** RegularExpression Id. */
  int WEBSITE = 6;
  /** RegularExpression Id. */
  int URL = 7;
  /** RegularExpression Id. */
  int EST = 8;
  /** RegularExpression Id. */
  int YEAR = 9;
  /** RegularExpression Id. */
  int GPS = 10;
  /** RegularExpression Id. */
  int COORDINATES = 11;
  /** RegularExpression Id. */
  int LONGITUDE = 12;
  /** RegularExpression Id. */
  int LATITUDE = 13;
  /** RegularExpression Id. */
  int LONGDEGREE = 14;
  /** RegularExpression Id. */
  int LATDEGREE = 15;
  /** RegularExpression Id. */
  int MINUTES = 16;
  /** RegularExpression Id. */
  int SECONDS = 17;
  /** RegularExpression Id. */
  int FACULTYNAME = 18;
  /** RegularExpression Id. */
  int STUDENTS = 19;
  /** RegularExpression Id. */
  int NUMSTUDENTS = 20;
  /** RegularExpression Id. */
  int STAFF = 21;
  /** RegularExpression Id. */
  int NUMSTAFF = 22;
  /** RegularExpression Id. */
  int CODE = 23;
  /** RegularExpression Id. */
  int COURSEENTRY = 24;
  /** RegularExpression Id. */
  int COURSEID = 25;
  /** RegularExpression Id. */
  int COURSEPOINTS = 26;
  /** RegularExpression Id. */
  int LEFTCURLY = 27;
  /** RegularExpression Id. */
  int RIGHTCURLY = 28;
  /** RegularExpression Id. */
  int STRING = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<UNIVERSITYNAME>",
    "<WEBSITE>",
    "<URL>",
    "<EST>",
    "<YEAR>",
    "<GPS>",
    "<COORDINATES>",
    "<LONGITUDE>",
    "<LATITUDE>",
    "<LONGDEGREE>",
    "<LATDEGREE>",
    "<MINUTES>",
    "<SECONDS>",
    "<FACULTYNAME>",
    "<STUDENTS>",
    "<NUMSTUDENTS>",
    "<STAFF>",
    "<NUMSTAFF>",
    "<CODE>",
    "<COURSEENTRY>",
    "<COURSEID>",
    "<COURSEPOINTS>",
    "\"{\"",
    "\"}\"",
    "<STRING>",
  };

}
