/* Generated By:JavaCC: Do not edit this line. UniParserConstants.java */
package uni;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UniParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNIVERSITYNAME = 5;
  /** RegularExpression Id. */
  int WEBSITE = 6;
  /** RegularExpression Id. */
  int URL = 7;
  /** RegularExpression Id. */
  int EST = 8;
  /** RegularExpression Id. */
  int YEAR = 9;
  /** RegularExpression Id. */
  int GPS = 10;
  /** RegularExpression Id. */
  int DEG = 11;
  /** RegularExpression Id. */
  int EW = 12;
  /** RegularExpression Id. */
  int NS = 13;
  /** RegularExpression Id. */
  int SECONDS = 14;
  /** RegularExpression Id. */
  int FACULTY = 15;
  /** RegularExpression Id. */
  int STUDENTS = 16;
  /** RegularExpression Id. */
  int STAFF = 17;
  /** RegularExpression Id. */
  int CODE = 18;
  /** RegularExpression Id. */
  int CODENAME = 19;
  /** RegularExpression Id. */
  int COURSEID = 20;
  /** RegularExpression Id. */
  int COURSEPOINTS = 21;
  /** RegularExpression Id. */
  int DIGIT_3 = 22;
  /** RegularExpression Id. */
  int DIGIT_2 = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int LEFTCURLY = 26;
  /** RegularExpression Id. */
  int RIGHTCURLY = 27;
  /** RegularExpression Id. */
  int NAME = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"UNIVERSITY\"",
    "\"WEBSITE\"",
    "<URL>",
    "\"EST\"",
    "<YEAR>",
    "\"GPS\"",
    "\"deg\"",
    "<EW>",
    "<NS>",
    "<SECONDS>",
    "\"FACULTY\"",
    "\"STUDENTS\"",
    "\"STAFF\"",
    "\"CODE\"",
    "<CODENAME>",
    "<COURSEID>",
    "<COURSEPOINTS>",
    "<DIGIT_3>",
    "<DIGIT_2>",
    "<DIGIT>",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "<NAME>",
    "<NUMBER>",
  };

}
