/* Generated By:JavaCC: Do not edit this line. UniParser.java */
package uni;

public class UniParser implements UniParserConstants {

  final public void University() throws ParseException {
    jj_consume_token(UNIVERSITYNAME);
    UniversityData();
    label_1:
    while (true) {
      Faculty();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FACULTY:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(RIGHTCURLY);
    jj_consume_token(0);
  }

  final public void UniversityData() throws ParseException {
    jj_consume_token(EST);
    jj_consume_token(WEBSITE);
    jj_consume_token(GPS);
  }

  final public void Faculty() throws ParseException, ParseException {
        boolean students = false;
        boolean staff = false;
        boolean website = false;
        boolean code = false;
        Token t;
        String facultyName;
    jj_consume_token(FACULTY);
    t = jj_consume_token(STRING);
   facultyName = t.image;
    jj_consume_token(LEFTCURLY);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WEBSITE:
      case STUDENTS:
      case STAFF:
      case CODE:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STUDENTS:
        jj_consume_token(STUDENTS);
 if (students) {
   {if (true) throw new ParseException("Multiple students counts in faculty entry: " + facultyName);}
 } else {
   students = true;
 }
        break;
      case STAFF:
        jj_consume_token(STAFF);
  if (staff) {
   {if (true) throw new ParseException("Multiple staff counts in faculty entry: " + facultyName);}
 } else {
   staff = true;
 }
        break;
      case WEBSITE:
        jj_consume_token(WEBSITE);
 if (website) {
   {if (true) throw new ParseException("Multiple websites in faculty entry: " + facultyName);}
 } else {
   website = true;
        }
        break;
      case CODE:
        Code();
  if (!code) {
        code = true;
  }
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  if (!code) {
                {if (true) throw new ParseException("No code found in faculty entry: " + facultyName);}
        }
  if (!staff) {
                {if (true) throw new ParseException("No staff count found in faculty entry: " + facultyName);}
        }
  if (!students) {
                {if (true) throw new ParseException("No student count found in faculty entry: " + facultyName);}
        }
    jj_consume_token(RIGHTCURLY);
  }

  final public void Code() throws ParseException {
    jj_consume_token(CODE);
    jj_consume_token(STRING);
    jj_consume_token(LEFTCURLY);
    label_3:
    while (true) {
      CourseEntry();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COURSEID:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
    }
    jj_consume_token(RIGHTCURLY);
  }

  final public void CourseEntry() throws ParseException {
    jj_consume_token(COURSEID);
    jj_consume_token(STRING);
    jj_consume_token(COURSEPOINTS);
  }

  /** Generated Token Manager. */
  public UniParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[4];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x40000,0xa80040,0xa80040,0x1000000,};
   }

  /** Constructor with InputStream. */
  public UniParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public UniParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new UniParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public UniParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new UniParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public UniParser(UniParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(UniParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[29];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 4; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 29; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
